/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CarbonCredit__factory } from "./CarbonCredit__factory";
export { Test__factory } from "./Test__factory";
